### ISSUE TITLE
Kappa-architecture.com link is down

### ISSUE THREAD

**Issue by martinheidegger** [kappa-db/workshop#26]
https://kappa-architecture, as [linked here](https://github.com/kappa-db/workshop/blob/b5d7b9a6102461bfc76fbf28cbb1cf66628a00b1/problems/10a.md#kappa-architecture) is not available anymore. Should the link be removed or did the domain change?

**Comment by hackergrrl** [comment]
Looks like http://milinda.pathirage.org/kappa-architecture.com/ is still up though. I changed the link.
