### ISSUE TITLE
What is the contents license

### ISSUE THREAD

**Issue by martinheidegger** [kappa-db/workshop#3]
In the package.json I found the standard ISC license. What license does the content have?

**Comment by hackergrrl** [comment]
I think ISC is ok? Fine with me. cc @karissa @mafintosh

**Comment by mafintosh** [comment]
ya :+1:

**Comment by martinheidegger** [comment]
I was expecting a CC license but good to know its ISC, thanks!

**Comment by hackergrrl** [comment]
I wanna hear back from @karissa on this. We technically never chose a license.

**Comment by okdistribute** [comment]
Thanks for the ping @noffle. I agree that it's a good idea to have a CC license, I like CC-BY-SA

**Comment by hackergrrl** [comment]
Agreed. Updated package.json and README :tada:
