### ISSUE TITLE
Fix javascript syntax highlighting

### ISSUE THREAD

**Issue by ralphtheninja** [kappa-db/workshop#34]
~~When rendering the markdown files into html, the js styling doesn't work. What do you think about only using the markdown files? We can remove all the build code and just focus on writing the markdown files that already looks nice on github with respect to js style etc.~~

Fix the syntax highlighting in the built html

**Comment by hackergrrl** [comment]
What styling isn't working? I was just leafing through the first few pages and it seems to look ok?

**Comment by ralphtheninja** [comment]
Html version:

![Screenshot from 2022-02-05 11-37-56](https://user-images.githubusercontent.com/308049/152638693-b2fee2b5-d6aa-4bde-88b5-bf4c29d80b49.png)

Markdown version on github:

![Screenshot from 2022-02-05 11-38-08](https://user-images.githubusercontent.com/308049/152638700-2f06f1b7-f2a0-4600-ad01-3e34d6455130.png)

To me markdown on github simply looks better by default

**Comment by hackergrrl** [comment]
Oh, the syntax highlighting?

**Comment by ralphtheninja** [comment]
> Oh, the syntax highlighting?

Yep! It would be nice if we could get that working in the html. Either that or, just enable the markdown to be "surfable", since the links in the markdown pages point to html pages and not to markdown.

**Comment by ralphtheninja** [comment]
@hackergrrl Btw, I added a project board for kappa here https://github.com/orgs/kappa-db/projects/1

**Comment by hackergrrl** [comment]
@ralphtheninja Full disclosure, I don't expect to have any capacity for this project any time in the near future :)   So please go ahead with whatever changes you'd like to make that you feel will improve the accessibility & utility of this workshop. 💙

**Comment by ralphtheninja** [comment]
> @ralphtheninja Full disclosure, I don't expect to have any capacity for this project any time in the near future :) So please go ahead with whatever changes you'd like to make that you feel will improve the accessibility & utility of this workshop. blue_heart

Ok. Will do my best! :heart:

**Comment by ralphtheninja** [comment]
@vweevers What would you use to render a markdown file with js code blocks to get a syntax highlighting similar to githubs js blocks?

EDIT: nvm, found `highlight.js`

**Comment by ralphtheninja** [comment]
Slightly better:

![Screenshot from 2022-02-06 17-53-03](https://user-images.githubusercontent.com/308049/152691722-dc4c1399-12e0-4755-8009-293f86d13fc2.png)

**Comment by vweevers** [comment]
@ralphtheninja Hi! I see you're already done but FWIW [I used shiki for the common changelog website](https://github.com/vweevers/common-changelog/blob/84b31de06304f203cc7521fcc6b19cea7380fd35/website/build.mjs#L14)
